// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRX_tVBiSFYanLOPV1jD7xOknxOijY5cY',
    appId: '1:723463078990:web:71d1147332913919fe2f1f',
    messagingSenderId: '723463078990',
    projectId: 'chat-app-46c21',
    authDomain: 'chat-app-46c21.firebaseapp.com',
    storageBucket: 'chat-app-46c21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv63jUmsxgxfoRdwhoRqY1dgpmKUcyXng',
    appId: '1:723463078990:android:2d7d0356172f8911fe2f1f',
    messagingSenderId: '723463078990',
    projectId: 'chat-app-46c21',
    storageBucket: 'chat-app-46c21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOkESElB_cHqbI7ogbY8FDCWwfXkiMw1k',
    appId: '1:723463078990:ios:b3f8fc52dc2261adfe2f1f',
    messagingSenderId: '723463078990',
    projectId: 'chat-app-46c21',
    storageBucket: 'chat-app-46c21.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOkESElB_cHqbI7ogbY8FDCWwfXkiMw1k',
    appId: '1:723463078990:ios:b3f8fc52dc2261adfe2f1f',
    messagingSenderId: '723463078990',
    projectId: 'chat-app-46c21',
    storageBucket: 'chat-app-46c21.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRX_tVBiSFYanLOPV1jD7xOknxOijY5cY',
    appId: '1:723463078990:web:54d080dadeb3ed61fe2f1f',
    messagingSenderId: '723463078990',
    projectId: 'chat-app-46c21',
    authDomain: 'chat-app-46c21.firebaseapp.com',
    storageBucket: 'chat-app-46c21.appspot.com',
  );

}